# Generated by Django 5.2.6 on 2025-09-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Discipline Records'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['term'], 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['-borrow_date'], 'verbose_name_plural': 'Library Records'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['term', 'subject'], 'verbose_name_plural': 'Performance Records'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_number'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student'),
        ),
        migrations.AlterField(
            model_name='library',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('late', 'Late')], default='borrowed', max_length=20),
        ),
        migrations.AlterField(
            model_name='library',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='teacher_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
