# Generated by Django 5.2.6 on 2025-09-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_discipline_options_alter_fee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Geography', 'Geography'), ('History', 'History'), ('CRE', 'CRE'), ('Business Studies', 'Business Studies'), ('Agriculture', 'Agriculture'), ('Computer Studies', 'Computer Studies'), ('Other', 'Other')], max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Study Books',
                'ordering': ['subject', 'title'],
            },
        ),
        migrations.AddField(
            model_name='library',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='students.studybook'),
        ),
    ]
