# Generated by Django 5.2.6 on 2025-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studybook_library_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studybook',
            name='available_copies',
        ),
        migrations.AddField(
            model_name='library',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fee',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
