# Generated by Django 5.2.6 on 2025-09-25 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studybook_available_copies_library_returned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={},
        ),
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fee',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='term',
            field=models.CharField(max_length=20),
        ),
    ]
